places = ('london','australia','sydney','korea','thailand','paris','bangkok')
print(places)
print("\n Here is the sorted list")
print(sorted(places))
print("\n Here is the original list")
print(places)
print("\n Here is the sorted reverse alphabetical order list")
print(sorted(places, reverse=True))
print("\n Here is the original list")
print(places)
places.reverse()
print("reversed_places_list:", places)
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)
